services:
  - type: web
    name: chat-app
    runtime: node
    buildCommand: npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: npm run start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
