services:
  - type: web
    name: chat-app-backend
    runtime: node
    buildCommand: npm install --prefix backend
    startCommand: npm run start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
